/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.24
 * Generated at: 2016-09-05 03:42:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import mack.entities.Usuario;
import java.util.List;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("mack.entities.Usuario");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta http-equiv=\"Content-Type\"\r\n");
      out.write("              content=\"text/html; charset=UTF-8\">\r\n");
      out.write("        <title>Pagina de Usuarios</title>\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"/appLp3/css/bootstrap.min.css\">\r\n");
      out.write("        <script src=\"/appLp3/js/jquery.min.js\"></script>\r\n");
      out.write("        <script src=\"/appLp3/js/bootstrap.min.js\"></script>\r\n");
      out.write("    </head>\r\n");
      out.write("    <body>\r\n");
      out.write("        ");

            List<Usuario> usuarios = (List<Usuario>) request.getAttribute("usuarios");
        
      out.write("\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <h2>Usuarios</h2>\r\n");
      out.write("            <h4>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mensagem}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h4>\r\n");
      out.write("            <table class=\"table table-striped\">\r\n");
      out.write("                <thead>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th>Nome</th>\r\n");
      out.write("                        <th>Sobrenome</th>\r\n");
      out.write("                        <th colspan=\"3\">Ações</th>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </thead>\r\n");
      out.write("                ");
if (usuarios.size() > 0) { 
      out.write("\r\n");
      out.write("                <tbody>\r\n");
      out.write("                    ");
 for (Usuario u : usuarios) {
      out.write("\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>");
      out.print(u.getNome());
      out.write("</td>\r\n");
      out.write("                        <td>");
      out.print(u.getSobrenome());
      out.write("</td>\r\n");
      out.write("                        <td><a href=\"FrontControllerServlet?control=Visualiza&id=");
      out.print(u.getId());
      out.write("&edit=0\" class=\"btn btn-primary\">Visualizar</a></td>\r\n");
      out.write("                        <td><a href=\"FrontControllerServlet?control=Visualiza&id=");
      out.print(u.getId());
      out.write("&edit=1\" class=\"btn btn-default\">Editar</a></td>\r\n");
      out.write("                        <td><a href=\"FrontControllerServlet?control=Deleta&id=");
      out.print(u.getId());
      out.write("\"  onclick=\"return confirm('Tem certeza ?')\" class=\"btn btn-danger\">Excluir</a></td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    ");
}
      out.write("\r\n");
      out.write("                </tbody>\r\n");
      out.write("                ");
}
      out.write("\r\n");
      out.write("            </table>\r\n");
      out.write("            <a href=\"cadastraUsuario.jsp\" class=\"btn btn-success\">Cadastro de Usuario</a>\r\n");
      out.write("            <a href=\"/appLp3/index.html\" class=\"btn btn-danger\">Voltar</a>\r\n");
      out.write("            <br><br>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"busca text-right\">\r\n");
      out.write("                <form class=\"form-inline\" action=\"FrontControllerServlet?control=Busca\" method=\"post\">\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label>Busca por Nome:</label>\r\n");
      out.write("                        <input class=\"form-control\" type=\"text\" placeholder=\"Digite o nome\" name=\"nomeBusca\" id=\"nomeBusca\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <input type=\"submit\" class=\"btn btn-warning\" value=\"Buscar\">\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("    </body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
